name: client-e2e-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  client:
    strategy:
      matrix:
        node-version: [14.5.x]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}


      - name: Start server in background
        working-directory: server
        run: |
          npm install
          npm start &
        env:
            PORT: 8080


      - name: Run and test client
        working-directory: client
        run: |
          npm install
          npm start &
          npm run cypress:test & 
          npm run test-playwright
        env:
          CI: true
          API_URI: http://localhost:3000/
