name: client-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  client:
    strategy:
      matrix:
        node-version: [14.5.x]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Test client
        working-directory: client
        run: |
          npm install
          npm run test-mocha
